services:
  node_app:
    container_name: node_app
    build: .
    image: izzy850/crud_app
    ports:
      - 5002:5002
    environment:
      - PG_DB=node_crud_db
      - PG_USER=izzy850
      - PG_PASSWORD=postgres
      - PG_HOST=node_db
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=node_crud_db
      - POSTGRES_USER=izzy850
      - POSTGRES_PASSWORD=postgres
    volumes:
      - node_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  node_db_data: {}
